/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

function Foundation() {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/formation-rock/model.gltf"
  );
  console.log(nodes, materials);
  return (
    <group ref={group} dispose={null}>
      <group position={[-2, -1, -3]} rotation={new THREE.Euler(0, -180, 0)}>
        <mesh
          geometry={nodes.formation_rock_1.geometry}
          material={materials["wood.008"]}
        />
        <mesh
          geometry={nodes.formation_rock_2.geometry}
          material={materials.sand}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/formation-rock/model.gltf"
);

export default Foundation;
